### ISSUE TITLE
User/Login.

### ISSUE THREAD

**Issue by eniosoeiro** [rigon/docker-sharelatex-full#1]
Great day,

Install your image successfully.

How to create the username and password?

**Comment by koppor** [comment]
Since this is based on the official sharelatex docker image, please follow their instructions at https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#creating-and-managing-users.

**Comment by rigon** [comment]
Open in your browser http://localhost:8080/launchpad
and configure the admin user from there.
