### ISSUE TITLE
Could you update your docker hub image? 

### ISSUE THREAD

**Issue by Jonn3y** [rigon/docker-sharelatex-full#2]
Hey, 

thanks for your work. Sadly your docker hub image is more than 2 years old.
Would be awesome if you could update it, so we all can use the latex TexLive installation :) 

Edit: Found out, the latest sharelatex image on hub.docker.com is based on texlive 2020., updating to 2021 would involve some more steps. 

Greetings!

**Comment by rigon** [comment]
Thanks for your interest! 😃 

I'm giving an update to the image, I hope it is useful for you.
I had this set up with automatic builds, but in the meantime they made that feature paid.
Now I'm enabling GitHub Actions, let's see if it does the trick.
